blank_issues_enabled: false
contact_links:
  - name: PolyScope Pro & PolyScope for Teams
    url: https://beyondcode.com
    about: 'For license and billing related questions, please send us an email to support@beyondco.de'
  - name: Check the docs
    url: https://getpolyscope.com/docs
    about: "This repository is for reporting bugs. If you need help with your first steps with PolyScope, check out the docs!"
  - name: Security vulnerabilities
    url: https://beyondcode.com
    about: If you want to report a security issue, please contact our support.
